### ISSUE TITLE
ValueError: File does not exist

### ISSUE THREAD

**Issue by Kimmm-pzl** [luxneuroimage/DBSegment#18]
This is my setting：
The input folder contains nifti format T1 weighted MRI in ".nii.gz" format. The output folder  is empty.
But after running DBSegment -i input_folder -o output_folder -mp path_to_model, 
I still encountered this ValueError: File code\DBSegment-main\test\mr_seg\preprocessed_v3\001.nii.gz does not exist!
Looking forward to your answer, thank you

**Comment by adhusch** [comment]
Hi!

Could you please provide some more information? In particular
- whats the system (OS, CPU) you are running on?
- whats the exact command line you tried (what where the values for input_folder and output_folder)?

Best
Andy

**Comment by Kimmm-pzl** [comment]
Thank you for your reply!

My answer to your two questions is as follows：
    1. I am using the windows system and cpu on the local computer, and plan to try a larger dataset on the linux server with the GPU
    2. I created "mr_data" as the input folder, and put a scan of T1 001.nii.gz into it, "mr_seg" as the output folder, and "models" as the folder to store the model. I then ran the command line code DBSegment -i ./test/mr_data -o ./test/mr_seg -mp ./test/models
    Then the model is automatically downloaded, and then the above error occurs.

Best
Kim

**Comment by adhusch** [comment]
Hello,

thank you! The tool is not test very intensely on windows (but it _should_ work).

Could you please state what the _full path_ to your current folder "." is (e.g. starting with C:\ ...)? Does it for example contain whitespaces?

Best
Andreas

**Comment by Kimmm-pzl** [comment]
I'm sorry I was busy with other things last week and didn't reply to you!

The full path to my current folder "." is C:\Users\23669\Desktop\医学图像\图像分割\code\DBSegment-main\test

By the way, I would like to ask if you have published the dataset you annotated. If I want to train my network, do I have to  download from the public dataset link you provided and manually annotate it myself?

Thank you for your attention to this matter. I eagerly anticipate your response!

Best
Kim

**Comment by Kimmm-pzl** [comment]
Hello,

I ran this command without error on the linux server, but filename_seg.nii.gz was not generated. The 001.nii.gz under the preprocessed_v3 file of mr_seg is more in line with the segmentation effect of 30 brain regions after being checked by mricro software.

The folder structure is as follows:

mr_data:.
├─preprocessed_v3
│  │  001_0000.nii.gz
├─001.nii.gz

mr_seg:.
├─preprocessed_v3
│  │  001.nii.gz
│  │  plans.pkl
├─001_brainmask.nii.gz
├─001.nii.gz

Thanks again and look forward to your reply!

Best
Kim

**Comment by adhusch** [comment]
Hi Kim,

great that you could try it on linux. We are trying to reproduce the error on the windows system. Did you try to run it with the files in a path that have no chinese letters included? Maybe there is a problem with the unicode path expansion across platforms.

Your linux output without the `_seg` postfix should be correct in the current version distributed via `pip`. Adding `_seg`was just done recently here in the Master branch and is not released yet to the version in pip.

Best
Andy

**Comment by Kimmm-pzl** [comment]
Hello Andy,

Thanks for your reply and clear answer!

I have another important question to ask: has your paper published the labeled training set? If not, is it necessary to download public datasets and manually label them to train a model in this field? Through simple thesis research, I would like to ask is it that there are very few labeled datasets published in this field?

Thanks again for your reply!

Best
Kim

**Comment by adhusch** [comment]
For licensing reasons it might be nessesary to download the source datasets on your own. We can check if we could release the labels we've generated using the conventional registration based pipeline. Alternativly we might also be able to release labels produced using DBSegment, i will have a look into this. Its more a legal than a technical question.

**Comment by Kimmm-pzl** [comment]
Thanks for your reply, it helped me a lot!

Best
Kim
